[package]
name = "pimoroni-trackball"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rp-hal = "0.0.2"
nb = "1.0.0"